import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 'calc(100vh - var(--header-height, 70px) - 60px)',
    padding: '40px 20px',
    boxSizing: 'border-box',
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  },
  card: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    padding: '40px',
    width: '100%',
    maxWidth: '540px',
    boxSizing: 'border-box',
    color: 'var(--text-primary)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    margin: '0 0 12px 0',
    color: 'var(--text-primary)',
  },
  subtitle: {
    fontSize: '14px',
    color: '#94a3b8',
    lineHeight: '1.6',
    margin: '0 0 28px 0',
  },
  spinnerContainer: {
    marginBottom: '24px',
  },
  spinner: {
    width: '50px',
    height: '50px',
    border: '4px solid rgba(56, 189, 248, 0.1)',
    borderTop: '4px solid #38bdf8',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  successIcon: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    background: 'rgba(16, 185, 129, 0.15)',
    border: '2px solid #10b981',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#10b981',
    marginBottom: '20px',
    boxShadow: '0 0 20px rgba(16, 185, 129, 0.25)',
  },
  errorIcon: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    background: 'rgba(239, 68, 68, 0.15)',
    border: '2px solid #ef4444',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ef4444',
    marginBottom: '20px',
    boxShadow: '0 0 20px rgba(239, 68, 68, 0.25)',
  },
  svgIcon: {
    width: '32px',
    height: '32px',
  },
  detailsBox: {
    width: '100%',
    background: 'rgba(15, 23, 42, 0.5)',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '30px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    textAlign: 'left',
    boxSizing: 'border-box',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '14px',
  },
  detailLabel: {
    color: '#94a3b8',
  },
  detailValue: {
    color: '#f8fafc',
    fontFamily: 'monospace',
  },
  badgeSuccess: {
    background: 'rgba(16, 185, 129, 0.2)',
    color: '#34d399',
    fontSize: '12px',
    fontWeight: 'bold',
    padding: '3px 8px',
    borderRadius: '6px',
    border: '1px solid rgba(16, 185, 129, 0.3)',
  },
  errorBox: {
    width: '100%',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    borderRadius: '10px',
    padding: '16px',
    marginBottom: '30px',
    textAlign: 'center',
    boxSizing: 'border-box',
  },
  errorText: {
    color: '#f87171',
    fontSize: '14px',
    fontWeight: '500',
  },
  form: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    marginBottom: '20px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    textAlign: 'left',
  },
  inputLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#cbd5e1',
    paddingLeft: '4px',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    background: 'var(--bg-inset)',
    border: '1px solid var(--border-color)',
    borderRadius: '6px',
    color: 'var(--text-primary)',
    fontSize: '15px',
    boxSizing: 'border-box',
    transition: 'all 0.2s ease',
    outline: 'none',
  },
  inputHelp: {
    fontSize: '11px',
    color: '#64748b',
    paddingLeft: '4px',
  },
  buttonPrimary: {
    width: '100%',
    padding: '14px',
    background: 'var(--accent-blue)',
    border: 'none',
    borderRadius: '6px',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  buttonSecondary: {
    padding: '14px 20px',
    background: 'rgba(255, 255, 255, 0.08)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    color: '#f8fafc',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    flex: '1',
  },
  buttonOutline: {
    width: '100%',
    padding: '12px',
    background: 'transparent',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    borderRadius: '8px',
    color: '#94a3b8',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    marginTop: '10px',
  },
  actionGroup: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    marginTop: '10px',
  },
};
